---
namespace: iamgini
name: system_utils
version: 0.4.0
readme: README.md
authors:
  - Gineesh Madapparambath <net.gini@gmail.com>
description: Ansible Collection to manage systems and services
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - demos
  - ansible
  - devops
dependencies: {}
repository: https://github.com/iamgini/ansible-collection-system-utils
documentation: https://github.com/iamgini/ansible-collection-system-utils
homepage: https://github.com/iamgini/ansible-collection-system-utils
issues: https://github.com/iamgini/ansible-collection-system-utils/issues

#build_ignore:
#- .gitignore
#- changelogs/.plugin-cache.yaml
