---
# tasks file for add_user
- name: Create new user on managed node
  user:
    name: "{{ new_user_name }}"
    password: "{{ new_user_password | password_hash('sha512') }}"
    groups: wheel
    append: yes

- name: Add key to managed node
  authorized_key:
    user: "{{ new_user_name }}"
    key: "{{ new_user_public_key }}"
    manage_dir: yes
  when:
    - new_user_public_key is defined
    - new_user_public_key != ''

- name: Add sudo entries for new user
  copy:
    content: "{{ new_user_name }} ALL=(ALL) NOPASSWD: ALL"
    dest: "/etc/sudoers.d/{{ new_user_name }}"
